language: objective-c
osx_image: xcode9.2

before_script:
  - export LANG=en_US.UTF-8
  - gem install cocoapods -v '1.8.4'
script:
  - cd ./Testing/Xcode-desktop
  - pod install
  - xcodebuild -workspace YapDatabaseTesting.xcworkspace -scheme YapDatabaseTesting clean
  - xcodebuild -workspace YapDatabaseTesting.xcworkspace -scheme YapDatabaseTesting -configuration release test
